@startuml





/' Objects '/

enum Messagetype {
	INT
	LONG
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Dependency relationships '/





/' Nested objects '/



@enduml
