@startuml





/' Objects '/

class SerialPort {
	+SerialPort()
	+SerialPort(const char* uartName, int baudrate_)
	-setup_port(int baud, int data_bits, int stop_bits, bool parity, bool hardware_control) : bool
	-uart_name : const char*
	-baudrate : int
	-fd : int
	-open_port(const char* port) : int
	-read_port(uint8_t& cp) : int
	+Mav_Recive(std::vector<mavlink_message_t>& message, std::vector<mavlink_status_t>& status) : uint8_t
	+Mav_Request_Data(uint8_t MAVStreams, uint16_t MAVRates, int MavStreamSize, int MavRateSize) : uint8_t
	+send_heartbeat() : uint8_t
	+send_some(mavlink_message_t message) : uint8_t
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Dependency relationships '/





/' Nested objects '/



@enduml
